### ISSUE TITLE
Invalid hex string

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#99]
Saw this on the contribution tx... haven't been able to replicate consistently:

![image](https://user-images.githubusercontent.com/54227730/120396794-0660a700-c2ec-11eb-865b-a1dad26f1f6c.png)

`Invalid hex string` error coming up during initial contribution submission. 

```
Vue warn]: Error in v-on handler (Promise/async): "TypeError: Invalid hex string"

found in

---> <ContributionModal> at src/components/ContributionModal.vue
       <VueJsModal> at src/components/Modal.vue
         <ModalsContainer> at src/components/ModalsContainer.vue
           <MobileTabs> at src/components/MobileTabs.vue vue.runtime.esm.js:619
TypeError: Invalid hex string
    hexWrite index.js:799
    write index.js:873
    fromString index.js:233
    from index.js:134
    from index.js:149
    bigInt2Buffer index.js:32
    formatPrivKeyForBabyJub index.js:149
    genPubKey index.js:181
    genKeypair index.js:192
    Keypair index.js:122
    createMessage maci.ts:30
    contribute ContributionModal.vue:202
    step tslib.es6.js:100
    verb tslib.es6.js:81
    fulfilled tslib.es6.js:71
vue.runtime.esm.js:1888
```

**Comment by samajammin** [comment]
Just hit this in #134 trying to review the PR locally... 🤔

**Comment by samajammin** [comment]
@corwintines @pettinarip curious if you folks have encountered this issue at all...

**Comment by pettinarip** [comment]
Not yet. Not that specific bug.

**Comment by ryancreatescopy** [comment]
@samajammin I think I was getting this fairly regularly... I fixed it by doing:

```
  await userRegistry.addUser(contributor1.getAddress())
  await userRegistry.addUser(contributor2.getAddress())
  await userRegistry.addUser('0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266')
```

in `DeployTestRound.ts`  

Basically add your MetaMask manually under the 2 existing contributor 1&2 on line 80...

Have managed to get through transactions by doing a combo of the above and:
- resetting account
- ensure I remove all projects from cart (in local storage) and re-adding them...

Even then it still doesn't always work so I restart node and do the above steps again.

**Comment by samajammin** [comment]
Tried a combination of those steps to no avail:
- Clearing out application storage
- Resetting MetaMask account
- Restarting local server
Started consistently hitting this error on the 1st transaction.

Strangely, what did work was switching my MetaMask account from `contributor1` to `contributor2` & going through those steps. Now I'm able to make transactions with this account.

**Comment by samajammin** [comment]
Interesting - a new edge case: I was able to make contribution txs but got this errors during the reallocation tx:

![Image 2021-06-17 at 2 21 50 PM](https://user-images.githubusercontent.com/8097623/122474000-73746d80-cf77-11eb-8d49-a1db93f63e08.jpg)

Still can't seem to consistently reproduce this error. Not sure what the root cause is here 🤔

**Comment by samajammin** [comment]
Hey @xuhcc - have you ever seen this error? I can't seem to figure out what's causing this.

**Comment by xuhcc** [comment]
@samajammin this looks similar to https://github.com/clrfund/monorepo/issues/348. Fixed in MACI 0.7.4

**Comment by samajammin** [comment]
Thanks @xuhcc - I commented on that issue. Do you mind reopening it? These errors above are all on MACI 0.7.4.

**Comment by weijiekoh** [comment]
@wackerow What's the commit hash of `ethereum/clrfund` that the error occurs on?

I'm trying reproduce the error in `create-react-app` without any luck. Maybe it depends on the setup. e.g. there may be a misbehaving polyfill.

**Comment by samajammin** [comment]
Thanks @weijiekoh - I'll retest but I continue to encounter this (latest `develop` commit hash: `a74ca3a1bc07a10e8861ec6da2220806c3459438`).

**Comment by wackerow** [comment]
@weijiekoh Yeah, also getting this still on latest `develop` branch, currently at commit b4f4034

Have been using `contributor1` account which had been working for a while, where all three transactions could be executed properly. Have recently noticed the above bug where the approval and the transfer go through, but then hangs on the vote message. Reloading the page makes it appear as though you've contributed, but your votes haven't gone through. "Reallocating" still worked in those cases, which ended up being the first set of votes submitted. 

Now getting the same `Invalid hex string` error when trying to submit a contribution again (same as original screenshot errors). Tried switching to `contributor2` with same issues. Using MetaMask, and have reset the accounts.

**Comment by weijiekoh** [comment]
@samajammin , Paul and I chatted and we found that the solution is to run `yarn` again to update the MACI packages to 0.7.4. Let me know how this turns out for you!

**Comment by wackerow** [comment]
This seems to be working, thanks @weijiekoh! Closing for now, can reopen if this doesn't fix for anyone.
